@extends('layouts.index')
@section('content')
<!-- Hero Area Start -->
<section class="padding-y-lg  pt-36">
    <header class="container max-width-xs margin-bottom-lg pt-12 pb-8 bg-gray-100">
        <div class="text-center">
            <h2 class="section-heading wow fadeInDown animated" data-wow-delay="0.3s"
                style="visibility: visible;-webkit-animation-delay: 0.3s; -moz-animation-delay: 0.3s; animation-delay: 0.3s;">
                TERMS OF SERVICE</h2>
            Last Updated April 18th, 2021
        </div>
    </header>
    <div class="container max-width-adaptive-sm mb-10">
        <div class="text-component line-height-lg v-space-md">
            <div class="mb-10">
                <p class="text-gray-600 mb-2">In terms of Information Technology Act, 2000, this document is an
                    electronic record. Being generated by a computer system it does not require any physical or digital
                    signatures.</p>
                <p class="text-gray-600 mb-2">Please read these Terms and Conditions of Use ("Terms") carefully. These
                    Terms, along with the others found on our application, include our policy for acceptable use of
                    application, its content, the content posted on the application, your rights, obligations and
                    restrictions regarding your use of this application. </p>
                <p class="text-gray-600 mb-2">By accessing this service, you accept, without limitation or
                    qualification, all the Terms applicable to the application, as amended from time to time. You are
                    only authorized to use application and its services if you agree to abide by all applicable laws and
                    to these Terms. If you do not accept these Terms, you must discontinue use of this service.</p>
                <p class="text-gray-600 mb-2">Notwithstanding anything else to the contrary, it is hereby specified that
                    product or service availed by you shall be subject to specific terms governing such transaction,
                    over and above the terms set forth herein. </p>
                <p class="text-gray-600 mb-2">LoginMojo is a product of Version# Technologies LLP</p>
                <p class="text-gray-600 mb-2">Version# Technologies LLP (“LoginMojo”, “LoginMojo.com”, “Version#”, “we”,
                    “us”, or “our”) provides a Software as a Service (SaaS) that allows its customers to use our
                    WhatsApp messaging service to register / authenticate their customers while using their website /
                    mobile app. </p>
                <p class="text-gray-600 mb-2">This LoginMojo Terms of Service (the “Agreement”) is an agreement between
                    the our Customers and LoginMojo, together the “Parties” and each, a “Party”, and is entered the date
                    the Customer signs up for a LoginMojo account through the LoginMojo.com website (the “Effective
                    Date”).</p>
            </div>




            <div class="mb-10">
                <h3 class="service-title">Modifications to the Service Terms and Fees</h3>

                <p class="text-gray-600 mb-2">We reserve the right, in our sole discretion, to terminate the access to
                    the application and the related services or any portion thereof at any time, without notice. </p>
                <p class="text-gray-600 mb-2">We reserves the right to change our monthly/annually fees upon 30 days
                    notice. Fee change will be notified per email to all our subscribers and will be reflected on the
                    pricing page at LoginMojo.com/#pricing.</p>
                <p class="text-gray-600 mb-2">We may modify these Terms from time to time and such modification will be
                    effective upon posting on this application. You agree to be bound to any changes to these Terms when
                    you use this application after any such modification is posted. It is important that you review
                    these Terms regularly to ensure you are updated as to any changes made. </p>
                <p class="text-gray-600 mb-2"></p>

            </div>
            <div class="mb-10">
                <h3 class="service-title">Use of Trademark License and Logo</h3>

                <p class="text-gray-600 mb-2">During the Term, Customer hereby grants us a worldwide, non-exclusive,
                    non-transferable and non-sub-licensable (other than to affiliates) royalty-free licence to use
                    Customer’s trademarks and logos made available to us by Customer as part of this Agreement, solely
                    in connection with the marketing, advertising, and promotion of the LOGINMOJO Solution, including
                    listing the Customer and the Customer Application on the LOGINMOJO Website; and only in accordance
                    with Customer’s reasonable trademark usage guidelines, as updated by Customer from time to time.
                    Customer may require LOGINMOJO to cease using Customer’s trademarks and logos if, in the reasonable
                    opinion of Customer, the continued display of Customer’s trademarks and logos would cause a
                    materially adverse effect on Customer’s image and the goodwill associated therewith.</p>
                <p class="text-gray-600 mb-2"></p>

            </div>
            <div class="mb-10">
                <h3 class="service-title">Intellectual property </h3>

                <p class="text-gray-600 mb-2">We shall own and retain the complete Intellectual Property rights in the
                    (i) Services and grant user a non-exclusive, non-transferable, limited license to use the
                    application only for the purpose of receiving the Services and/or utilizing the deliverables in
                    accordance with the terms herein as well as other terms on the Application.</p>
                <p class="text-gray-600 mb-2">We expressly reserves all rights, title, and interest in, and Customer
                    will not acquire any right, title or interest in: (i) the LOGINMOJO Solution (or any part thereof)
                    and any other materials or content provided by LOGINMOJO under this Agreement, including any and all
                    Modifications to any of the foregoing; and (ii) all intellectual property rights in any of the
                    foregoing (clauses (i) and (ii) are collectively, the “LOGINMOJO Property”), in each case. All
                    right, title and interest in the LOGINMOJO Property will remain with LOGINMOJO (or LOGINMOJO’s third
                    party suppliers, as applicable). Customer may not copy, modify, adapt, reproduce, distribute,
                    reverse engineer, decompile, or disassemble any aspect of the Service which LOGINMOJO or its
                    suppliers own. Customer agrees not to resell, duplicate, reproduce or exploit any part of the
                    Service without the express written permission of LOGINMOJO. For greater certainty, the LOGINMOJO
                    Property is licensed and not “sold” to Customer. </p>
                <p class="text-gray-600 mb-2">LOGINMOJO claims no intellectual property rights over the Content you
                    upload or provide to the Service.</p>


            </div>
            <div class="mb-10">
                <h3 class="service-title">LOGINMOJO’s Right to Use Customer Data</h3>
                <p class="text-gray-600 mb-2">Customer acknowledges and agrees that LOGINMOJO may store, use, reproduce,
                    Modify, and transfer to its subcontractors, Customer Data, including Personal Data, solely in
                    connection with delivering the Services under this Agreement. Customer further acknowledges and
                    agrees that LOGINMOJO may store, use, reproduce, Modify, and transfer data that is not related to an
                    identified or identifiable natural person, including aggregated or de-identified data, without
                    limitation, for its internal business purposes, including but not limited to such purposes as
                    analytics, quality assurance, product and service improvement, and new product and service
                    development. Customer agrees to cause any Administrative User, Customer’s Client, and Chat
                    Participant to agree to the terms.</p>


            </div>
            <div class="mb-10">
                <h3 class="service-title">Customer Responsibilities</h3>


                <p class="text-gray-600 mb-2">Customers are responsible for maintaining the privacy and security of your
                    accounts. LOGINMOJO will not be held liable for any damage or loss that may result from your failure
                    to protect your login information, including your password.</p>
                <p class="text-gray-600 mb-2">The Customer is fully responsible for all activities that occur under the
                    account and any other actions taken in connection with the account. You are responsible for all
                    Content send and activity that occurs under your account (even when Content is sent by others to
                    your account). </p>
                <p class="text-gray-600 mb-2">LOGINMOJO may, but have no obligation to, remove Content and Accounts
                    containing Content that we determine in our sole discretion are unlawful, offensive, threatening,
                    libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party’s
                    intellectual property or these Terms of Use.</p>


            </div>
            <div class="mb-10">
                <h3 class="service-title">Email and Web Support</h3>

                <p class="text-gray-600 mb-2">Customer will generally have access to LOGINMOJO’s technical support from
                    10:00am to 7:00pm IST (GMT+5:30) on weekdays (other than holidays observed by LOGINMOJO) through
                    email support by mailing us on support@versionhash.com</p>


            </div>
            <div class="mb-10">
                <h3 class="service-title">Fees and Payment</h3>

                <p class="text-gray-600 mb-2">Fees: Customer will pay to LOGINMOJO the applicable fees described on the
                    LoginMojo Website (the “Fees”) during the Term in accordance with the payment terms set out herein.
                </p>
                <p class="text-gray-600 mb-2">Payment Terms:</p>
                <ul class="text-gray-600 ml-10">
                    <li class="mb-2">– All Fees shall be in U.S. Dollars;</li>
                    <li class="mb-2">– The Fees start immediately after you make the payment. The onboarding verification time is
                        counted
                        towards the subscription.</li>
                    <li class="mb-2">– There will be no refunds or credits for partial months of service, upgrade/downgrade refunds,
                        or
                        refunds for months unused with an open account. In order to treat everyone equally, no
                        exceptions will
                        be made.</li>
                    <li class="mb-2">– Payment obligations hereunder are not subject to any set-off or withholding rights whatsoever,
                        any and
                        all of which are hereby expressly waived by Customer.</li>
                    <li class="mb-2">– Disputed Invoices or Charges. If Customer in good faith disputes any portion of a LOGINMOJO
                        invoice or
                        charge, Customer may provide a dispute notice to LOGINMOJO with written documentation
                        identifying and
                        substantiating the disputed amount within fifteen (15) days from receipt of the applicable
                        invoice or
                        charge, and if applicable, at the time it pays the undisputed portion of such invoice, withhold
                        payment
                        of such disputed portion. If Customer does not report or does not provide such substantiating
                        documentation within that period, Customer shall be deemed to have waived its right to dispute
                        any and
                        all portions of that invoice.</li>
                    <li class="mb-2">– Late Payment. Except for bona fide disputed amounts, any failure to make a payment of any Fees
                        or
                        taxes in strict conformity with the requirements entitle LOGINMOJO to suspend, in whole or in
                        part,
                        access to Services, until such payment is received. Additionally, LOGINMOJO shall assess and
                        Customer
                        shall pay a charge, compounded monthly, of the lesser of (a) 1.5% per month (19.56% per year) or
                        (b) the
                        highest amount allowed by law on all past due amounts (except amounts disputed). Furthermore,
                        upon any
                        such failure all outstanding amounts shall become due and payable without further delay.</li>
                    <li class="mb-2">– Any cancellation of your Account will result in the deactivation or deletion of your Account
                        or your
                        access to your Account, and the forfeiture and relinquishment of all Content in your Account.
                        This
                        information cannot be recovered from LOGINMOJO once your account is cancelled.</li>
                    <li class="mb-2">– Taxes. The Fees set out in this Agreement do not include applicable taxes, duties,
                        withholdings,
                        tariffs, levies, customs, capital or income taxes or other governmental charges or expenses,
                        including
                        but not limited to value added tax, sales tax, consumption tax and similar taxes or duties as
                        well as
                        any current or future municipal, state, federal or provincial taxes, and Customer will pay,
                        indemnify
                        and hold harmless LOGINMOJO from same, other than taxes based on the net income or profits of
                        LOGINMOJO.</li>
                </ul>

            </div>
            <div class="mb-10">
                <h3 class="service-title">TERMS FOR TERMINATION</h3>
                <p class="text-gray-600 mb-2">LoginMojo may refuse service to anyone for any reason at any time.</p>
                <p class="text-gray-600 mb-2">LOGINMOJO makes no warranties regarding (i) your ability to use the
                    Service, (ii) your satisfaction with the Service, (iii) that the Service will be available at all
                    times, uninterrupted, and error-free (iv), the accuracy of mathematical calculations performed by
                    the Service, and (v) that bugs or errors in the Service will be corrected. LOGINMOJO and its
                    affiliates are neither responsible nor liable for any direct, indirect, incidental, consequential,
                    special, exemplary, punitive or other damages arising out of or relating in any way to your use of
                    the Service. Your sole remedy for dissatisfaction with the Service is to stop using the Service.</p>

            </div>
            <div class="mb-10">
                <h3 class="service-title">Term of Agreement </h3>
                <p class="text-gray-600 mb-2">This Agreement will commence on the Effective Date and continue to be in
                    effect until your subscription has been terminated in accordance with the terms Customer agreed to
                    on the LOGINMOJO website at time of signup (the “Term”). For greater certainty, if Customer has
                    subscribed to an ongoing subscription, then such subscription will automatically renew at its expiry
                    for the same period of time, at the then-current subscription rate described on the LOGINMOJO
                    Website. </p>

            </div>
            <div class="mb-10">
                <h3 class="service-title">Termination for Convenience</h3>
                <p class="text-gray-600 mb-2">Either Party may elect to terminate this Agreement and your subscription
                    to LOGINMOJO services as of the end of your then current Term by providing notice, on or prior to
                    the date thirty (30) days preceding the end of such Term. For clarity, unless this Agreement and
                    your subscription is so terminated, your subscription will renew for a Term equivalent in length to
                    the then expiring Term.</p>
                <p class="text-gray-600 mb-2">LOGINMOJO will use all reasonable efforts to contact you directly via
                    email to warn you prior to suspension or termination of your account. Any suspected fraudulent,
                    abusive, or illegal activity that may be grounds for termination of your use of Service, may be
                    referred to appropriate law enforcement authorities. LOGINMOJO shall not be liable to You or any
                    third party for any modification, suspension or discontinuation of the Service. </p>

            </div>
            <div class="mb-10">
                <h3 class="service-title">Termination for Cause</h3>

                <p class="text-gray-600 mb-2">A Party may terminate this Agreement for cause (a) upon thirty (30) days’
                    written notice to the other Party of a material breach if such breach remains uncured at the
                    expiration of such period; or (b) if the other Party becomes the subject of a petition in bankruptcy
                    or any other proceeding relating to insolvency, receivership, liquidation or assignment for the
                    benefit of creditors. If this Agreement is terminated by you in accordance with this section,
                    LOGINMOJO will, to the extent permitted by applicable law, refund you any prepaid fees covering the
                    remainder of the Term after the effective date of termination. If this Agreement is terminated by
                    LOGINMOJO in accordance with this section, you will pay any unpaid fees covering the remainder of
                    the Term. In no event will termination relieve you of your obligation to pay any fees payable to
                    LOGINMOJO for the period prior to the effective date of termination.</p>

            </div>
            <div class="mb-10">
                <h3 class="service-title">Termination for Non-payment</h3>

                <p class="text-gray-600 mb-2">LOGINMOJO reserves the right to suspend Services if the Customer fails to
                    timely pay any undisputed amounts due to LOGINMOJO under this Agreement, but only after LOGINMOJO
                    notifies Customer of such failure and such failure continues for thirty (30) calendar days after
                    such notification. Suspension of Services shall not release Customer of its payment obligations
                    under this Agreement. Customer agrees that LOGINMOJO shall not be liable to Customer or to any third
                    party for any liabilities, claims or expenses arising from or relating to suspension of the Services
                    resulting from Customer’s non-payment, unless LOGINMOJO suspends the Services without giving
                    Customer 30 calendar-days written notice to rectify its failure to pay.</p>
                <p class="text-gray-600 mb-2">Termination will result in the deactivation or deletion of your Account or
                    your access to your Account, and the forfeiture and relinquishment of all Content in your Account.
                    This information cannot be recovered from LOGINMOJO once your account is terminated. </p>

            </div>
            <div class="mb-10">
                <h3 class="service-title">Refunds and Termination Charges</h3>

                <p class="text-gray-600 mb-2">No refunds or credits for Fees will be provided if you elect to terminate
                    this Agreement prior to the end of your Term. If you terminate this Agreement prior to the end of
                    your Term, or LOGINMOJO effects such termination, in addition to other amounts you may owe
                    LOGINMOJO, you must immediately pay any then unpaid Fees associated with the remainder of your Term.
                    This amount will not be payable by you in the event you terminate as a result of a material breach
                    of this Agreement by LOGINMOJO, provided that you provide advance notice of such breach to LOGINMOJO
                    and afford LOGINMOJO not less than thirty (30) days to reasonably cure such breach.</p>


            </div>
            <div class="mb-10">
                <h3 class="service-title">Limitation of Liabilities</h3>

                <p class="text-gray-600 mb-2">The Parties acknowledge that the following provisions have been negotiated
                    by them and reflect a fair allocation of risk and form an essential basis of the bargain and will
                    survive and continue in full force and effect despite any failure of consideration or of an
                    exclusive remedy. In no event will the total aggregate liability of LoginMojo in connection with or
                    under this agreement exceed the amount of fees paid by customer in the prior 12 month period
                    immediately preceding the event giving rise to the claim or USD200, whichever is the lesser. </p>

            </div>
            <div class="mb-10">
                <h3 class="service-title">Force majeure</h3>
                <p class="text-gray-600 mb-2">We shall not be responsible for delay or default in the performance due to
                    contingencies beyond our control, such as (including but not limited to) losses caused directly or
                    indirectly by exchange or market rulings, suspension of trading, fire, flood, civil commotion,
                    earthquake, war, strikes, failure of the systems, failure of the internet links or government /
                    regulatory action.</p>

            </div>
            <div class="mb-10">
                <h3 class="service-title">Jurisdiction </h3>
                <p class="text-gray-600 mb-2">This agreement is governed and construed in accordance with the Laws of
                    Union of India. You hereby irrevocably consent to the exclusive jurisdiction and venue of courts in
                    Mumbai, Maharashtra, India, in all disputes arising out of or relating to the use of our
                    application/services. Use of our application/services is unauthorized in any jurisdiction that does
                    not give effect to all provisions of these terms and conditions, including without limitation this
                    paragraph. You agree to indemnify and hold the Company, its subsidiaries, affiliates, officers,
                    directors, employees, and representatives harmless from any claim, demand, or damage, including
                    reasonable attorneys' fees, asserted by any third party due to or arising out of your use of or
                    conduct on the application/services.</p>
            </div>



        </div>
        <div class="text-component line-height-lg v-space-md">
            <p>Version# Technologies LLP</p>
            <p>Mumbai, India</p>
        </div>
    </div>
</section>
@stop
